### ISSUE TITLE
Remove 60 Hz hum from select recordings?

### ISSUE THREAD

**Issue by scottveirs** [coastal-science/call-catalog-viewer#31]
Hey @JKBF ! 

Using the dictionary this morning to analyze J pod pass this morning at Val's place, I noticed a handful of your recordings have some prominent system noise at low frequencies. For example, there is substantial [60 Hz hum in this S22 example](https://orca.research.sfu.ca/catalogue/catalogs/srkw-call-catalogue-files/media/S22-L-4.wav)). You can see the 60 Hz harmonic and fundamentals in this power spectrum from the last ~20% of the clip:

<img width="1792" alt="Screenshot 2023-09-14 at 9 44 14 AM" src="https://github.com/coastal-science/call-catalog-viewer/assets/14044595/48eba7fc-9928-4fc9-ae7e-6857f2b46513">

**Would you like me to use Audacity to reduce or remove the noise, e.g. with a high-pass filter?**

Here is a [new version of the S22-L-4.wav sample after post-processing](https://www.orcasound.net/data/raw/SRKW-Ford-Osborne-tapes/S22-L-4-test.wav) (12 dB de-noising, 48 dB high-pass filter at 1kHz, another 12 dB de-noising, and then amplification to standard levels).

If you think it's worthwhile now, I could propose a list and potential improvements. Once you approve the list, I could download the samples, process, and return to a (post-processed) archive of SRKW samples.

I personally think this sort of cleaning of field recordings is low priority for the first version of this new SRKW catalog, and could be postponed for a future version. I'm more interested in getting a new tool into the "wild" and available for Orcasound community scientists, but wanted to flag noisier recordings as an issue to possibly be addressed at some point!

**Comment by JKBF** [comment]
Hi Scott,

That particular S22 example is from captive whales at Pedder Bay in 1973.  Not sure how it was recorded.

Cheers

John

John K.B. Ford
Research scientist (emeritus)
Pacific Biological Station
Fisheries and Oceans Canada

Co-chair, COSEWIC Marine Mammals Species Specialist Subcommittee

**Comment by scottveirs** [comment]
Thanks for the metadata, @JKBF . That's an old recording!

What do you think about my question: 

`Would you like me to use Audacity to reduce or remove the noise, e.g. with a high-pass filter?`

**Comment by JKBF** [comment]
Hi Scott,

Thanks, I can run that file and a couple of others that need it through a high pass and replace them.

Cheers,

John

John K.B. Ford
Research scientist (emeritus)
Pacific Biological Station
Fisheries and Oceans Canada

Co-chair, COSEWIC Marine Mammals Species Specialist Subcommittee

**Comment by VWJF** [comment]
I can confirm that @JKBF updated the S22-L-3 and S22-L-4 wav files.

Closing this issue
