### ISSUE TITLE
Viewer load too slow on low-bandwidth connection

### ISSUE THREAD

**Issue by scottveirs** [coastal-science/call-catalog-viewer#8]
I tried to access the catalogue (Chrome, MacBook) when I was visiting Orcasound Lab on the west side of San Juan Island. At this location in Washington, the download bandwidth is pretty limited (5 MB/s down; 0.1 MB/s up).

The catalog loaded slowly, taking 30-60 seconds to complete, possibly due to other traffic on the LAN. This seems to be due to the images having a file size of about 100kB and the initial/default view of catalogue involving some 90 images. That's about 10MB which could result in a similar performance issue on e.g. mobile devices.

<img width="1792" alt="Screen Shot 2022-09-07 at 3 15 28 PM" src="https://user-images.githubusercontent.com/14044595/188994189-593866de-e72f-427b-9c50-e56913c1fb7e.png">
<img width="1792" alt="Screen Shot 2022-09-07 at 3 15 42 PM" src="https://user-images.githubusercontent.com/14044595/188994219-216d8911-6386-4aaf-8722-8494f1b483f4.png">
<img width="464" alt="Screen Shot 2022-09-07 at 3 17 44 PM" src="https://user-images.githubusercontent.com/14044595/188994248-a61938f2-510b-4871-83df-bc414fee0b91.png">

I'm pretty sure I had already loaded the catalogue in this location on this browser+device, so am wondering whether there is a way to force the catalogue code to use cached images first, rather than downloading again?

Alternatively, this issue could motivate a simplified initial/default view -- e.g. one that presents only one example of each call type first, then gives an option to download/view more examples subsequently...

**Comment by VWJF** [comment]
Addressed with PR #30 and [srkw-call-catalogue-files PR #11](https://github.com/sfu-bigdata/srkw-call-catalogue-files/pull/11)

**Comment by VWJF** [comment]
Closing this issue. Will create a new issue if it becomes a concern again.
